server:
  port: 8082

spring:
  application:
    name: operador
  datasource:
    url: jdbc:mysql://mysql-operador:3306/operadordb
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: operador
    password: operador
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
